# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170112_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.Token'),
        ),
    ]
